name: build

on:
  - push
  - pull_request

jobs:
  createAndTestTemplateCRA:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Settings to fix problem on Ubuntu
        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf
      - run: sudo sysctl -p
      - name: Create create-next-app from downloaded template
        run: npx create-next-app my-app -e https://github.com/EliEladElrom/next-must-have-libraries .
      - name: No need to fail due to warnings using CI=false
        run: CI= npm run build
